version: 2
build:
  os: ubuntu-20.04
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
    pre_install:
      # unshallow so the version works
      - git fetch --unshallow
        # see https://github.com/readthedocs/readthedocs.org/issues/8201
      - git update-index --assume-unchanged ci/requirements/docs.yml docs/conf.py
      # install regionmask, needs to be editable
      - pip install -e .
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt

formats: []
